---
title: "A Component-Wise Perspective on Multiobjective Evolutionary Algorithms based on Decomposition"
subtitle: "MOEADr tuning experiments"
author: F. Campelo, L.S. Batista, C. Aranha
output: html_document
---

This folder contains the routines for the tuning experiments using the MOEADr package, as part of the results section of the manuscript. In the experiments we follow the protocol suggested in [@Bezerra2016]: we employ two distinct benchmark sets, DTLZ [@Deb2005] and WFG [@Huband2006], and use disjoint sets for tuning and evaluation by partitioning the number of variables used, with:

$$
n_v^{tune} \in \left\{20,\dotsc,60\right\} \backslash n_v^{test}
$$
and 

$$ 
n_v^{test} \in \left\{30,40,50\right\}
$$


For the experiments, we defined:

- Constraint handling: FIXED
- $\phi$ parameter of differential mutation: FIXED (Phi = NULL)
- stop criterion: FIXED (maxevals)
- between 2 and 4 variation operators, with:
    - first 2 operators $\in \left\{diffmut,binrec,sbx,polymut\right\}$
    - third operator $\in \left\{diffmut,binrec,sbx,polymut,truncate,none\right\}$
    - fourth operator $\in \left\{localsearch,none\right\}$
- Operator parameters independently tuned for each position (e.g., SBX can appear in first and third option places, with independently tuned $\eta_X$)
- local search done probabilistically (using $\gamma_{ls}\in(0,0.5)$) when local search is present.


Not included in tuning:
- ipbi (couldn't validate the source code)
- msld (no need, since dealing with 2 objectives)






## References

---
references:
- id: Bezerra2016
  title: 'Automatic Component-wise Design of Multi-objective Evolutionary
Algorithms'
  author: 
    - family: Bezerra
      given: Leonardo
    - family: López-Ibañez
      given: Manuel
    - family: Stützle
      given: Thomas
  container-title: 'IEEE Trans. Evol. Comp.'
  volume: 20
  issue: 3
  page: 403-417
  issued:
    year: 2016
    month: 8
  URL: 'http://dx.doi.org/10.1109/TEVC.2015.2474158'
  DOI: 10.1109/TEVC.2015.2474158
  type: article-journal

- id: Deb2005
  title: 'Scalable test problems for evolutionary multiobjective optimization'
  author: 
    - family: Deb
      given: Kalyanmoy
    - family: Thiele
      given: Lothar
    - family: Laumanns
      given: Marco
    - family: Eckart
      given: Zitzler
  container-title: 'Evolutionary Multiobjective Optimization: Theoretical Advances and Applications'
  page: 105-145
  issued:
    year: 2005
    month: 1
  URL: 'http://dx.doi.org/10.1007/1-84628-137-7_6'
  DOI: 10.1007/1-84628-137-7_6
  type: chapter
  
- id: Huband2006
  title: 'A review of multiobjective test problems and a scalable test problem toolkit'
  author: 
    - family: Huband
      given: S
    - family: Hingston
      given: P
    - family: Barone
      given: L
    - family: While
      given: L
  container-title: 'IEEE Trans. Evol. Comp.'
  volume: 10
  issue: 5
  page: 477-506
  issued:
    year: 2006
    month: 10
  URL: 'http://dx.doi.org/10.1109/TEVC.2005.861417'
  DOI: 10.1109/TEVC.2005.861417
  type: article-journal
---
